"""Create user table

Revision ID: a4a3fd039e49
Revises: 
Create Date: 2023-08-27 14:33:45.926670

"""
from alembic import op
import sqlalchemy as sa
import datetime as dt


# revision identifiers, used by Alembic.
revision = "a4a3fd039e49"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    user_table = op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("email", sa.String(length=120), nullable=False),
        sa.Column("password", sa.String(length=128), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_users_username"), ["username"], unique=True
        )

    # ### end Alembic commands ###

    op.bulk_insert(
        user_table,
        [
            {
                "username": "admin",
                "email": "admin@admin.com",
                "password": "$2b$12$cvH/msM8uhsGmJ6JYnOsEeDghTh/lkcoTSkIsBrrbLcV.l5r7r3cq",
                "created_at": dt.datetime.now(),
                "updated_at": dt.datetime.now(),
            }
        ],
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_username"))
        batch_op.drop_index(batch_op.f("ix_users_email"))

    op.drop_table("users")
    # ### end Alembic commands ###
