name: artemis
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2023.05.30
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - ncurses=6.4
  - openssl=3.0.9
  - pip=23.1.2
  - python=3.11.4
  - readline=8.2
  - setuptools=67.8.0
  - sqlite=3.41.2
  - tk=8.6.12
  - tzdata=2023c
  - wheel=0.38.4
  - xz=5.4.2
  - zlib=1.2.13
  - pip:
      - alembic==1.11.2
      - aniso8601==9.0.1
      - astroid==2.15.6
      - blinker==1.6.2
      - cffi==1.15.1
      - click==8.1.6
      - cryptography==40.0.2
      - dill==0.3.7
      - flask==2.3.2
      - flask-cors==4.0.0
      - flask-jwt-extended==4.5.2
      - flask-marshmallow==0.15.0
      - flask-migrate==4.0.4
      - flask-restful==0.3.10
      - flask-sqlalchemy==3.0.5
      - gunicorn==21.2.0
      - isort==5.12.0
      - itsdangerous==2.1.2
      - jinja2==3.1.2
      - lazy-object-proxy==1.9.0
      - mako==1.2.4
      - markupsafe==2.1.3
      - marshmallow==3.20.1
      - marshmallow-sqlalchemy==0.29.0
      - mccabe==0.7.0
      - packaging==23.1
      - platformdirs==3.10.0
      - pycparser==2.21
      - pyjwt==2.8.0
      - pylint==2.17.5
      - python-dotenv==0.21.1
      - python-dotenv-vault==0.6.1
      - pytz==2023.3
      - six==1.16.0
      - sqlalchemy==2.0.19
      - tomlkit==0.12.1
      - typing-extensions==4.7.1
      - werkzeug==2.3.6
      - wrapt==1.15.0
